export const FREE_SHIPPING_THRESHOLD_PLN = 149;
export const INPOST_LOCKER_PRICE_PLN = 17.99;

export const FREE_SHIPPING_THRESHOLD_GROSZ =
  FREE_SHIPPING_THRESHOLD_PLN * 100;
export const INPOST_LOCKER_PRICE_GROSZ = Math.round(
  INPOST_LOCKER_PRICE_PLN * 100,
);

export const INPOST_LOCKER_CODE_PATTERN = /^[A-Z0-9-]{3,20}$/;
