import {defineField, defineType} from "sanity";

export const categoryType = defineType({
  name: "category", title: "Categories", type: "document",
  groups: [
    {name: "basic", title: "Category", default: true},
    {name: "landing", title: "Landing page"},
    {name: "polish", title: "Polish / Polski"},
    {name: "seo", title: "SEO"},
  ],
  fields: [
    defineField({name: "title", title: "Name", type: "string", group: "basic", validation: (rule) => rule.required()}),
    defineField({name: "titlePl", title: "Name (Polish)", type: "string", group: "polish"}),
    defineField({name: "slug", title: "Slug", type: "slug", group: "basic", options: {source: "title"}, validation: (rule) => rule.required()}),
    defineField({name: "description", title: "Short description", type: "text", rows: 3, group: "landing"}),
    defineField({name: "descriptionPl", title: "Short description (Polish)", type: "text", rows: 3, group: "polish"}),
    defineField({name: "eyebrow", title: "Small heading", type: "string", group: "landing"}),
    defineField({name: "eyebrowPl", title: "Small heading (Polish)", type: "string", group: "polish"}),
    defineField({name: "heroTitle", title: "Landing page headline", type: "string", group: "landing", validation: (rule) => rule.max(90)}),
    defineField({name: "heroTitlePl", title: "Landing page headline (Polish)", type: "string", group: "polish", validation: (rule) => rule.max(90)}),
    defineField({name: "heroText", title: "Landing page introduction", type: "text", rows: 4, group: "landing", validation: (rule) => rule.max(320)}),
    defineField({name: "heroTextPl", title: "Landing page introduction (Polish)", type: "text", rows: 4, group: "polish", validation: (rule) => rule.max(320)}),
    defineField({name: "image", title: "Landing page hero image", type: "image", group: "landing", options: {hotspot: true}, fields: [{name: "alt", title: "Alternative text", type: "string"}]}),
    defineField({name: "storyTitle", title: "Story heading", type: "string", group: "landing"}),
    defineField({name: "storyTitlePl", title: "Story heading (Polish)", type: "string", group: "polish"}),
    defineField({name: "storyText", title: "Story text", type: "text", rows: 4, group: "landing"}),
    defineField({name: "storyTextPl", title: "Story text (Polish)", type: "text", rows: 4, group: "polish"}),
    defineField({name: "seoTitle", title: "SEO title", type: "string", group: "seo", validation: (rule) => rule.max(60)}),
    defineField({name: "seoDescription", title: "SEO description", type: "text", rows: 3, group: "seo", validation: (rule) => rule.max(160)}),
    defineField({name: "seoTitlePl", title: "SEO title (Polish)", type: "string", group: "seo", validation: (rule) => rule.max(60)}),
    defineField({name: "seoDescriptionPl", title: "SEO description (Polish)", type: "text", rows: 3, group: "seo", validation: (rule) => rule.max(160)}),
    defineField({name: "sortOrder", title: "Display order", type: "number", group: "basic", initialValue: 100}),
  ],
  preview: {select: {title: "title", media: "image"}},
});
