import {defineArrayMember, defineField, defineType} from "sanity";

const option = defineArrayMember({
  type: "object",
  name: "productOption",
  fields: [
    defineField({name: "name", title: "Option name", type: "string", validation: (rule) => rule.required()}),
    defineField({name: "namePl", title: "Option name (Polish)", type: "string"}),
    defineField({name: "sku", title: "SKU", type: "string"}),
    defineField({name: "stock", title: "Stock", type: "number", initialValue: 0, validation: (rule) => rule.min(0)}),
  ],
  preview: {select: {title: "name", subtitle: "sku"}},
});

export const productType = defineType({
  name: "product",
  title: "Products",
  type: "document",
  groups: [
    {name: "basic", title: "Basic", default: true},
    {name: "polish", title: "Polish / Polski"},
    {name: "media", title: "Photos"},
    {name: "variants", title: "Sizes & colours"},
    {name: "commerce", title: "Price & stock"},
    {name: "care", title: "Fit & care"},
    {name: "socialProof", title: "Reviews & customer photos"},
    {name: "seo", title: "SEO"},
  ],
  fields: [
    defineField({name: "name", title: "Product name", type: "string", group: "basic", validation: (rule) => rule.required().max(100)}),
    defineField({name: "namePl", title: "Product name (Polish)", type: "string", group: "polish", validation: (rule) => rule.max(100)}),
    defineField({name: "slug", title: "URL slug", type: "slug", group: "basic", options: {source: "name", maxLength: 96}, validation: (rule) => rule.required()}),
    defineField({name: "shortDescription", title: "Short description", type: "string", group: "basic", validation: (rule) => rule.max(160)}),
    defineField({name: "description", title: "Full description", type: "array", group: "basic", of:[defineArrayMember({type:"block",styles:[{title:"Normal",value:"normal"},{title:"Heading 3",value:"h3"}],lists:[{title:"Bullets",value:"bullet"}]})], validation: (rule) => rule.required()}),
    defineField({name: "descriptionPl", title: "Full description (Polish)", type: "array", group: "polish", of:[defineArrayMember({type:"block",styles:[{title:"Normal",value:"normal"},{title:"Heading 3",value:"h3"}],lists:[{title:"Bullets",value:"bullet"}]})]}),
    defineField({name: "category", title: "Category", type: "reference", to: [{type: "category"}], group: "basic", validation: (rule) => rule.required()}),
    defineField({name: "collections", title: "Collections", type: "array", of: [{type: "reference", to: [{type: "collection"}]}], group: "basic"}),
    defineField({name: "petType", title: "Pet type", type: "string", group: "basic", options: {layout: "radio", list: [{title: "Dog", value: "dog"}, {title: "Cat", value: "cat"}, {title: "Dogs & cats", value: "both"}]}, validation: (rule) => rule.required()}),
    defineField({
      name: "status",
      title: "Sales status",
      type: "string",
      group: "basic",
      initialValue: "hidden",
      description: "New products stay hidden. Choose Active only after the name, description, price, category, main photo, sizes and colours are complete.",
      options: {list: [{title: "Active — ready to sell", value: "active"}, {title: "Coming soon", value: "comingSoon"}, {title: "Hidden — still editing", value: "hidden"}, {title: "Sold out", value: "soldOut"}]},
      validation: (rule) => rule.required(),
    }),
    defineField({name: "image", title: "Main photo", type: "image", group: "media", options: {hotspot: true}, fields: [{name: "alt", title: "Alternative text", type: "string", validation: (rule) => rule.required()}], validation: (rule) => rule.required()}),
    defineField({name: "gallery", title: "Photo gallery", type: "array", group: "media", of: [{type: "image", options: {hotspot: true}, fields: [{name: "alt", title: "Alternative text", type: "string"}]}]}),
    defineField({name: "sizes", title: "Sizes", type: "array", group: "variants", of: [option], validation: (rule) => rule.required().min(1)}),
    defineField({name: "colors", title: "Colours", type: "array", group: "variants", of: [defineArrayMember({type: "object", name: "colour", fields: [defineField({name: "name", title: "Colour name", type: "string", validation: (rule) => rule.required()}), defineField({name: "namePl", title: "Colour name (Polish)", type: "string"}), defineField({name: "hex", title: "Colour code", type: "string", description: "Example: #E8795E"})], preview: {select: {title: "name", subtitle: "hex"}}})], validation: (rule) => rule.required().min(1)}),
    defineField({name: "price", title: "Price", type: "number", group: "commerce", validation: (rule) => rule.required().positive()}),
    defineField({name: "compareAtPrice", title: "Previous price", type: "number", group: "commerce", description: "Shown crossed out during a sale", validation: (rule) => rule.positive()}),
    defineField({name: "currency", title: "Currency", type: "string", group: "commerce", initialValue: "PLN", readOnly: true}),
    defineField({name: "sku", title: "Main SKU", type: "string", group: "commerce"}),
    defineField({name: "featured", title: "Featured on homepage", type: "boolean", group: "commerce", initialValue: false, description: "If no active product is selected, the first active products are shown automatically."}),
    defineField({name: "badge", title: "Product badge", type: "string", group: "commerce", options: {list: ["New", "Bestseller", "Limited", "Sale", "Handmade"]}}),
    defineField({name: "material", title: "Material", type: "string", group: "care"}),
    defineField({name: "careInstructions", title: "Care instructions", type: "text", rows: 3, group: "care"}),
    defineField({name: "fitNotes", title: "Fit notes", type: "text", rows: 3, group: "care"}),
    defineField({name: "sizeGuide", title: "Size guide", type: "reference", to: [{type: "sizeGuide"}], group: "care"}),
    defineField({name:"relatedProducts",title:"Related products",type:"array",group:"basic",of:[{type:"reference",to:[{type:"product"}]}],validation:r=>r.unique().max(4)}),
    defineField({
      name: "reviews",
      title: "Approved customer reviews",
      type: "array",
      group: "socialProof",
      description: "Only entries marked Approved are shown on the product page. Never add a review without the customer's permission.",
      of: [defineArrayMember({
        type: "object",
        name: "productReview",
        fields: [
          defineField({name: "customerName", title: "Customer name", type: "string", validation: (rule) => rule.required()}),
          defineField({name: "petName", title: "Pet name", type: "string"}),
          defineField({name: "rating", title: "Rating", type: "number", initialValue: 5, validation: (rule) => rule.required().integer().min(1).max(5)}),
          defineField({name: "quote", title: "Review (English)", type: "text", rows: 3, validation: (rule) => rule.required().max(320)}),
          defineField({name: "quotePl", title: "Review (Polish)", type: "text", rows: 3, validation: (rule) => rule.max(320)}),
          defineField({name: "photo", title: "Customer photo", type: "image", options: {hotspot: true}, fields: [{name: "alt", title: "Alternative text", type: "string"}]}),
          defineField({name: "approved", title: "Approved for the website", type: "boolean", initialValue: false}),
        ],
        preview: {select: {title: "petName", customer: "customerName", rating: "rating", media: "photo"}, prepare: ({title, customer, rating, media}) => ({title: title || customer || "Customer review", subtitle: `${"★".repeat(rating || 0)} · ${customer || "Customer"}`, media})},
      })],
    }),
    defineField({name: "seoTitle", title: "SEO title", type: "string", group: "seo", validation: (rule) => rule.max(60)}),
    defineField({name: "seoDescription", title: "SEO description", type: "text", rows: 3, group: "seo", validation: (rule) => rule.max(160)}),
    defineField({name: "sortOrder", title: "Display order", type: "number", initialValue: 100, hidden: true}),
  ],
  orderings: [{title: "Display order", name: "sortOrder", by: [{field: "sortOrder", direction: "asc"}]}, {title: "Newest", name: "newest", by: [{field: "_createdAt", direction: "desc"}]}],
  preview: {select: {title: "name", price: "price", status: "status", media: "image"}, prepare: ({title, price, status, media}) => ({title: title || "Untitled product", subtitle: `${price ?? "—"} PLN · ${status ?? "needs review"}`, media})},
});
