import {defineArrayMember, defineField, defineType} from "sanity";

const option = defineArrayMember({
  type: "object",
  name: "productOption",
  fields: [
    defineField({name: "name", title: "Option name", type: "string", validation: (rule) => rule.required()}),
    defineField({name: "sku", title: "SKU", type: "string"}),
    defineField({name: "stock", title: "Stock", type: "number", initialValue: 0, validation: (rule) => rule.min(0)}),
  ],
  preview: {select: {title: "name", subtitle: "sku"}},
});

export const productType = defineType({
  name: "product",
  title: "Products",
  type: "document",
  groups: [
    {name: "basic", title: "Basic", default: true},
    {name: "media", title: "Photos"},
    {name: "variants", title: "Sizes & colours"},
    {name: "commerce", title: "Price & stock"},
    {name: "care", title: "Fit & care"},
    {name: "seo", title: "SEO"},
  ],
  fields: [
    defineField({name: "name", title: "Product name", type: "string", group: "basic", validation: (rule) => rule.required().max(100)}),
    defineField({name: "slug", title: "URL slug", type: "slug", group: "basic", options: {source: "name", maxLength: 96}, validation: (rule) => rule.required()}),
    defineField({name: "shortDescription", title: "Short description", type: "string", group: "basic", validation: (rule) => rule.max(160)}),
    defineField({name: "description", title: "Full description", type: "text", rows: 6, group: "basic", validation: (rule) => rule.required()}),
    defineField({name: "category", title: "Category", type: "reference", to: [{type: "category"}], group: "basic", validation: (rule) => rule.required()}),
    defineField({name: "collections", title: "Collections", type: "array", of: [{type: "reference", to: [{type: "collection"}]}], group: "basic"}),
    defineField({name: "petType", title: "Pet type", type: "string", group: "basic", options: {layout: "radio", list: [{title: "Dog", value: "dog"}, {title: "Cat", value: "cat"}, {title: "Dogs & cats", value: "both"}]}, validation: (rule) => rule.required()}),
    defineField({name: "status", title: "Sales status", type: "string", group: "basic", initialValue: "active", options: {list: [{title: "Active", value: "active"}, {title: "Coming soon", value: "comingSoon"}, {title: "Hidden", value: "hidden"}, {title: "Sold out", value: "soldOut"}]}}),
    defineField({name: "image", title: "Main photo", type: "image", group: "media", options: {hotspot: true}, fields: [{name: "alt", title: "Alternative text", type: "string", validation: (rule) => rule.required()}], validation: (rule) => rule.required()}),
    defineField({name: "gallery", title: "Photo gallery", type: "array", group: "media", of: [{type: "image", options: {hotspot: true}, fields: [{name: "alt", title: "Alternative text", type: "string"}]}]}),
    defineField({name: "sizes", title: "Sizes", type: "array", group: "variants", of: [option], validation: (rule) => rule.required().min(1)}),
    defineField({name: "colors", title: "Colours", type: "array", group: "variants", of: [defineArrayMember({type: "object", name: "colour", fields: [defineField({name: "name", title: "Colour name", type: "string", validation: (rule) => rule.required()}), defineField({name: "hex", title: "Colour code", type: "string", description: "Example: #E8795E"})], preview: {select: {title: "name", subtitle: "hex"}}})], validation: (rule) => rule.required().min(1)}),
    defineField({name: "price", title: "Price", type: "number", group: "commerce", validation: (rule) => rule.required().positive()}),
    defineField({name: "compareAtPrice", title: "Previous price", type: "number", group: "commerce", description: "Shown crossed out during a sale", validation: (rule) => rule.positive()}),
    defineField({name: "currency", title: "Currency", type: "string", group: "commerce", initialValue: "PLN", readOnly: true}),
    defineField({name: "sku", title: "Main SKU", type: "string", group: "commerce"}),
    defineField({name: "featured", title: "Featured on homepage", type: "boolean", group: "commerce", initialValue: false}),
    defineField({name: "badge", title: "Product badge", type: "string", group: "commerce", options: {list: ["New", "Bestseller", "Limited", "Sale", "Handmade"]}}),
    defineField({name: "material", title: "Material", type: "string", group: "care"}),
    defineField({name: "careInstructions", title: "Care instructions", type: "text", rows: 3, group: "care"}),
    defineField({name: "fitNotes", title: "Fit notes", type: "text", rows: 3, group: "care"}),
    defineField({name: "sizeGuide", title: "Size guide", type: "reference", to: [{type: "sizeGuide"}], group: "care"}),
    defineField({name: "seoTitle", title: "SEO title", type: "string", group: "seo", validation: (rule) => rule.max(60)}),
    defineField({name: "seoDescription", title: "SEO description", type: "text", rows: 3, group: "seo", validation: (rule) => rule.max(160)}),
    defineField({name: "sortOrder", title: "Display order", type: "number", initialValue: 100, hidden: true}),
  ],
  orderings: [{title: "Display order", name: "sortOrder", by: [{field: "sortOrder", direction: "asc"}]}, {title: "Newest", name: "newest", by: [{field: "_createdAt", direction: "desc"}]}],
  preview: {select: {title: "name", price: "price", status: "status", media: "image"}, prepare: ({title, price, status, media}) => ({title, subtitle: `${price ?? "—"} PLN · ${status ?? "active"}`, media})},
});
